export const dungeonEvents: string[] = [
  "The party stumbled upon a hidden treasure chest.",
  "A deadly trap was triggered! One hero took damage.",
  "They discovered a mysterious shrine that boosts strength.",
  "A wandering merchant offered rare goods.",
  "The party fought off a group of skeleton warriors.",
  "They found an ancient scroll of forgotten magic.",
  "A cursed statue drained some of their energy.",
  "One hero was poisoned by a venomous spider.",
  "The group rescued a lost adventurer who joined them.",
  "They found a shortcut deeper into the dungeon.",
  "A floor collapsed beneath them! They fell to a lower level.",
  "They uncovered a pile of gold coins and gems.",
  "An old diary revealed a clue about a boss's weakness.",
  "A magical trap swapped their health and mana.",
  "They discovered a healing fountain and recovered HP.",
  "A ghost whispered forgotten knowledge to the mage.",
  "A rare monster appeared and dropped epic loot.",
  "They triggered an ambush by dungeon bandits.",
  "An enchanted mirror showed them visions of the future.",
  "The ranger spotted and disarmed a hidden trap.",
  "A mimic disguised as a chest attacked them!",
  "They found a dark crystal that grants random buffs.",
  "A riddle-locked door tested their intellect.",
  "A sudden cave-in forced them to retreat early.",
  "They stumbled into a boss room unprepared!",
  "The dungeon air thickened — a magical storm is coming.",
  "A time portal briefly sent them to a strange era.",
  "They recovered a long-lost relic from the ruins.",
  "A goblin shaman cursed the party’s loot drop rate.",
  "The warrior had a vision of a future battle.",
  "They heard distant footsteps… something is stalking them.",
  "The rogue discovered a secret stash of potions.",
  "The dungeon guardian demanded a toll in gold.",
  "They uncovered a map showing an unexplored area.",
  "One hero tripped and dropped half the loot.",
  "An ancient spirit offered a trade: XP for gold.",
  "They found a glowing gem — but it hums ominously.",
  "A cursed altar offered power at a price.",
  "The bard’s song accidentally awoke the dead.",
  "They were chased by a horde of dungeon rats.",
  "A glowing rune branded one hero — temporarily boosting their stats."
];